### ISSUE TITLE
Search results failed to point to the correct link

### ISSUE THREAD

**Issue by forliuyifei** [probberechts/hexo-theme-cactus#256] opened 2020-11-10 03:36 UTC
![Screenshot_20201110-111146696](https://user-images.githubusercontent.com/53306807/98624429-c71b3a80-2348-11eb-94ad-7d0019c69159.jpg)
![Screenshot_20201110-113539661](https://user-images.githubusercontent.com/53306807/98624491-e4500900-2348-11eb-8fbd-9bf4ad735240.jpg)

The retrieval was successful

**Comment by probberechts** [comment] 2020-11-10 07:12
Duplicate of #247

**Closed by probberechts** 2020-11-10 07:12 UTC
