### ISSUE TITLE
About Search

### ISSUE THREAD

**Issue by linbuxiao** [probberechts/hexo-theme-cactus#246] opened 2020-09-24 18:45 UTC
After installing the search plugin, I can see the results when I click Search, but the jump will result in a 404 page. Why?My website is

:https://linbuxiao.github.io/.
I'd appreciate it if you could answer that

**Comment by probberechts** [comment] 2020-10-24 09:51
Duplicate of #247

**Closed by probberechts** 2020-10-24 09:51 UTC
